-- MySQL Script generated by MySQL Workbench
-- 09/17/20 11:16:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stusys
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stusys` ;

-- -----------------------------------------------------
-- Schema stusys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stusys` DEFAULT CHARACTER SET utf8 ;
USE `stusys` ;

-- -----------------------------------------------------
-- Table `stusys`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stusys`.`course` ;

CREATE TABLE IF NOT EXISTS `stusys`.`course` (
  `cno` CHAR(6) NOT NULL,
  `cname` VARCHAR(50) NULL,
  `cpno` CHAR(6) NULL,
  `ccredit` SMALLINT(2) NULL,
  PRIMARY KEY (`cno`),
  INDEX `cpno_idx` (`cpno` ASC),
  CONSTRAINT `cpno`
    FOREIGN KEY (`cpno`)
    REFERENCES `stusys`.`course` (`cno`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stusys`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stusys`.`teacher` ;

CREATE TABLE IF NOT EXISTS `stusys`.`teacher` (
  `tno` CHAR(8) NOT NULL,
  `tname` VARCHAR(8) NULL,
  `tsex` ENUM('男', '女') NULL,
  `tage` INT(4) NULL,
  `teb` VARCHAR(10) NULL,
  `tpt` NVARCHAR(10) NULL,
  `cno1` CHAR(6) NULL,
  `cno2` CHAR(6) NULL,
  `cno3` CHAR(6) NULL,
  `passwd` VARCHAR(20) NULL,
  PRIMARY KEY (`tno`),
  INDEX `cno1_idx` (`cno1` ASC),
  INDEX `cno2_idx` (`cno2` ASC),
  INDEX `cno3_idx` (`cno3` ASC),
  CONSTRAINT `cno1`
    FOREIGN KEY (`cno1`)
    REFERENCES `stusys`.`course` (`cno`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `cno2`
    FOREIGN KEY (`cno2`)
    REFERENCES `stusys`.`course` (`cno`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `cno3`
    FOREIGN KEY (`cno3`)
    REFERENCES `stusys`.`course` (`cno`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stusys`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stusys`.`department` ;

CREATE TABLE IF NOT EXISTS `stusys`.`department` (
  `dno` CHAR(3) NOT NULL,
  `dname` VARCHAR(30) NOT NULL,
  `dmanagerno` CHAR(8) NULL,
  PRIMARY KEY (`dno`),
  INDEX `dmanagerno_idx` (`dmanagerno` ASC),
  UNIQUE INDEX `dno_UNIQUE` (`dno` ASC),
  UNIQUE INDEX `dname_UNIQUE` (`dname` ASC),
  CONSTRAINT `dmanagerno`
    FOREIGN KEY (`dmanagerno`)
    REFERENCES `stusys`.`teacher` (`tno`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stusys`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stusys`.`student` ;

CREATE TABLE IF NOT EXISTS `stusys`.`student` (
  `sno` CHAR(9) NOT NULL,
  `sname` VARCHAR(8) NOT NULL,
  `ssex` ENUM('男', '女') NULL,
  `sage` INT(4) NULL,
  `sdept` VARCHAR(30) NULL,
  `passwd` VARCHAR(20) NULL,
  PRIMARY KEY (`sno`),
  INDEX `sdept_idx` (`sdept` ASC),
  CONSTRAINT `sdept`
    FOREIGN KEY (`sdept`)
    REFERENCES `stusys`.`department` (`dname`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stusys`.`sct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stusys`.`sct` ;

CREATE TABLE IF NOT EXISTS `stusys`.`sct` (
  `sno` CHAR(9) NOT NULL,
  `cno` CHAR(6) NOT NULL,
  `tno` CHAR(8) NOT NULL,
  `grade` INT(4) NULL,
  INDEX `cno_idx` (`cno` ASC),
  INDEX `tno_idx` (`tno` ASC),
  PRIMARY KEY (`sno`, `cno`, `tno`),
  CONSTRAINT `sno`
    FOREIGN KEY (`sno`)
    REFERENCES `stusys`.`student` (`sno`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `cno`
    FOREIGN KEY (`cno`)
    REFERENCES `stusys`.`course` (`cno`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `tno`
    FOREIGN KEY (`tno`)
    REFERENCES `stusys`.`teacher` (`tno`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stusys`.`teascourses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stusys`.`teascourses` ;

CREATE TABLE IF NOT EXISTS `stusys`.`teascourses` (
  `tno` CHAR(8) NOT NULL,
  `cno` CHAR(6) NOT NULL,
  PRIMARY KEY (`tno`, `cno`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



use stusys;
delimiter ##
-- 创建触发器
create trigger after_insert_student after insert on student for each row
begin
    -- 更新商品表的库存，这里只指定了更新第一件商品的库存
    insert images values(new.sno,"default.jpg");
end
##

delimiter ;