-- MySQL Script generated by MySQL Workbench
-- 09/05/20 01:07:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stusys
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stusys` ;

-- -----------------------------------------------------
-- Schema stusys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stusys` DEFAULT CHARACTER SET utf8 ;
USE `stusys` ;

-- -----------------------------------------------------
-- Table `stusys`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stusys`.`department` ;

CREATE TABLE IF NOT EXISTS `stusys`.`department` (
  `dno` CHAR(3) NOT NULL,
  `dname` VARCHAR(30) NOT NULL,
  `dmanagerno` CHAR(8) NULL,
  PRIMARY KEY (`dname`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stusys`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stusys`.`student` ;

CREATE TABLE IF NOT EXISTS `stusys`.`student` (
  `sno` CHAR(9) NOT NULL,
  `sname` VARCHAR(8) NULL,
  `ssex` CHAR(1) NULL,
  `sage` INT(4) NULL,
  `sdept` VARCHAR(30) NULL,
  PRIMARY KEY (`sno`),
  INDEX `sdept_idx` (`sdept` ASC),
  CONSTRAINT `sdept`
    FOREIGN KEY (`sdept`)
    REFERENCES `stusys`.`department` (`dname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stusys`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stusys`.`course` ;

CREATE TABLE IF NOT EXISTS `stusys`.`course` (
  `cno` CHAR(6) NOT NULL,
  `cname` VARCHAR(50) NULL,
  `cpno` CHAR(6) NULL,
  `ccredit` SMALLINT(2) NULL,
  PRIMARY KEY (`cno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stusys`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stusys`.`teacher` ;

CREATE TABLE IF NOT EXISTS `stusys`.`teacher` (
  `tno` CHAR(8) NOT NULL,
  `tname` VARCHAR(8) NULL,
  `tsex` ENUM('男', '女') NULL,
  `tage` INT(4) NULL,
  `teb` VARCHAR(10) NULL,
  `tpt` NVARCHAR(10) NULL,
  `cno1` CHAR(6) NULL,
  `cno2` CHAR(6) NULL,
  `cno3` CHAR(6) NULL,
  PRIMARY KEY (`tno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stusys`.`sct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stusys`.`sct` ;

CREATE TABLE IF NOT EXISTS `stusys`.`sct` (
  `sno` CHAR(9) NOT NULL,
  `cno` CHAR(6) NULL,
  `tno` CHAR(8) NULL,
  `grade` INT(4) NULL,
  PRIMARY KEY (`sno`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
